package com.example.danialchowdhry.ballgame;

import android.app.Activity;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;


/**
 * The game fragment. Displays a random number of balls
 * and asks the user to answer how many balls appear on screen.
 * The number of balls is generated by a parameter passed in
 * by the user
 */
public class Game extends Fragment {
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    // Random variable that determines the number of balls on
    // the screen
    private static int rando;

    private OnFragmentInteractionListener mListener;

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param newRando An int that will decide the new rando
     * @return A new instance of fragment Game.
     */
    public static Game newInstance(int newRando) {
        Game fragment = new Game();
        Bundle args = new Bundle();
        // Get rando set up as a field
        args.putInt(ARG_PARAM1, newRando);
        fragment.setArguments(args);
        return fragment;
    }

    public Game() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            // Set rando on creation
            rando = getArguments().getInt(ARG_PARAM1);
        }
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the view of the game fragment
        View imview = inflater.inflate(R.layout.fragment_game, container, false);
        // Get the image for the ball out so it can be edited
        ImageView image = (ImageView) imview.findViewById(R.id.ballView);
        // Assign it based on the random variable passed in by the caller fragment
        switch (rando) {
            case 0:
                image.setImageDrawable(getResources().getDrawable(R.drawable.ball0));
                break;
            case 1:
                image.setImageDrawable(getResources().getDrawable(R.drawable.ball1));
                break;
            case 2:
                image.setImageDrawable(getResources().getDrawable(R.drawable.ball2));
                break;
            case 3:
                image.setImageDrawable(getResources().getDrawable(R.drawable.ball3));
                break;
            case 4:
                image.setImageDrawable(getResources().getDrawable(R.drawable.balls));
                break;
            default:
                image.setImageDrawable(getResources().getDrawable(R.drawable.balls));
                break;
        }
        return imview;
    }

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        try {
            mListener = (OnFragmentInteractionListener) activity;
        } catch (ClassCastException e) {
            throw new ClassCastException(activity.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p/>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnFragmentInteractionListener {
        public void onFragmentInteraction(Uri uri);
    }

}
